version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: doc/source/conf.py
  fail_on_warning: true

conda:
    environment: doc/environment.yaml

python:
    install:
        - method: pip
          path: .
